declare module 'lumin' {
  namespace ui {
    enum SystemIcon {
      kActions = 0,
      kActionsLeft = 1,
      kActionsOff = 2,
      kActionsRight = 3,
      kAdd = 4,
      kAddressBook = 5,
      kAlbumAdd = 6,
      kAlbumRemove = 7,
      kAlphabetical = 8,
      kAnalytics = 9,
      kArrowDown = 10,
      kArrowLeft = 11,
      kArrowRight = 12,
      kArrowUp = 13,
      kAutoPlacement = 14,
      kBackspace = 15,
      kBattery = 16,
      kBlock = 17,
      kBlockCamera = 18,
      kBlockCookie = 19,
      kBlockLocation = 20,
      kBlockMicrophone = 21,
      kBluetooth = 22,
      kBluetoothOff = 23,
      kBookmark = 24,
      kBookmarkAdd = 25,
      kBrightness = 26,
      kCalendar = 27,
      kCamera = 28,
      kCameraIris = 29,
      kCarriageReturn = 30,
      kChat = 31,
      kCheck = 32,
      kCheckSelection = 33,
      kChevronDown = 34,
      kChevronLeft = 35,
      kChevronRight = 36,
      kChevronUp = 37,
      kClipboard = 38,
      kClock = 39,
      kClose = 40,
      kClosedCaption = 41,
      kCloud = 42,
      kCloudOff = 43,
      kCollection = 44,
      kController = 45,
      kCookie = 46,
      kCopy = 47,
      kCreditCard = 48,
      kCut = 49,
      kDoNotDisturb = 50,
      kDot = 51,
      kDownload = 52,
      kDownloadCloud = 53,
      kDropdown = 54,
      kEdit = 55,
      kEffectsPalette = 56,
      kEject = 57,
      kEmoji = 58,
      kEnter = 59,
      kExit = 60,
      kExtraction = 61,
      kEyeTracking = 62,
      kFastForward = 63,
      kFastForwardTenSecond = 64,
      kFile = 65,
      kFilter = 66,
      kFlag = 67,
      kFlagChina = 209,
      kFlagFrance = 210,
      kFlagGermany = 211,
      kFlagJapan = 212,
      kFlagSouthKorea = 213,
      kFlagUK = 214,
      kFlagUSA = 215,
      kFollow = 68,
      kFrame = 69,
      kGameController = 70,
      kGenericThreeDimensional = 71,
      kGrid = 72,
      kHamburger = 73,
      kHandOrientationLeft = 74,
      kHandOrientationRight = 75,
      kHeart = 76,
      kHeartAdd = 77,
      kHelp = 78,
      kHistory = 79,
      kHome = 80,
      kImage = 81,
      kInfo = 82,
      kKeyboard = 83,
      kKeyboardCapital = 84,
      kKeyboardLetter = 85,
      kKeyboardNumber = 86,
      kLink = 87,
      kListView = 88,
      kLocalAreaServer = 89,
      kMarqueeSelection = 90,
      kMerge = 91,
      kMesh = 92,
      kMicrophone = 93,
      kMicrophoneMute = 94,
      kMinimize = 95,
      kMobile = 96,
      kMore = 97,
      kMove = 98,
      kMultipleSelection = 99,
      kMusic = 100,
      kMusicPause = 101,
      kMusicPlay = 102,
      kNetworkServer = 103,
      kNext = 104,
      kNotification = 105,
      kObjectRecognition = 206,
      kOpenWith = 106,
      kOrigin = 107,
      kPassableWorld = 108,
      kPaste = 109,
      kPause = 110,
      kPermission = 111,
      kPerson = 112,
      kPersonAdd = 113,
      kPersonBlock = 114,
      kPersonFollow = 115,
      kPersonThree = 116,
      kPersonTwo = 117,
      kPersonUnFollow = 118,
      kPersonVoip = 119,
      kPhone = 120,
      kPhoneEndCall = 121,
      kPhoneIncomingCall = 122,
      kPhoneSwitchCall = 123,
      kPin = 124,
      kPlaceholderBluetooth = 125,
      kPlay = 126,
      kPlaylistRepeatOff = 127,
      kPlaylistRepeatOn = 128,
      kPlaylistRepeatSong = 129,
      kPlaylistShuffle = 130,
      kPlaylistShuffleOff = 203,
      kPower = 131,
      kPrevious = 204,
      kPrivacy = 132,
      kPrivateView = 133,
      kPublicView = 134,
      kRefresh = 135,
      kReplay = 136,
      kReport = 137,
      kRestoreMedia = 138,
      kRevolver = 139,
      kRewindTenSecond = 140,
      kScreenshot = 141,
      kSearch = 142,
      kSecurityLock = 143,
      kSecurityNotSecure = 144,
      kSecurityUnlock = 145,
      kSend = 146,
      kSettings = 147,
      kShare = 148,
      kShareScreen = 207,
      kShiftDisabled = 149,
      kShiftEnabled = 150,
      kShiftEnabledPermanent = 151,
      kSixDof = 152,
      kSleep = 153,
      kSlideshow = 154,
      kSnooze = 155,
      kSpace = 156,
      kStar = 157,
      kStop = 158,
      kStream = 159,
      kStreamOff = 160,
      kSummon = 161,
      kTablet = 208,
      kTabNew = 162,
      kTabNewImage = 163,
      kTabViewAll = 164,
      kTag = 165,
      kText = 166,
      kThumbsDown = 167,
      kThumbsDownLeft = 168,
      kThumbsDownRight = 169,
      kThumbsUp = 170,
      kThumbsUpLeft = 171,
      kThumbsUpRight = 172,
      kTopChart = 173,
      kTrash = 174,
      kUndoReply = 175,
      kUnknownDevice = 176,
      kUpdate = 177,
      kUpload = 178,
      kUploadCloud = 179,
      kView = 180,
      kViewSource = 181,
      kVoiceFeedback = 182,
      kVoip = 183,
      kVolume = 184,
      kVolumeMute = 185,
      kWarning = 186,
      kWifi = 187,
      kWifiNoBar = 188,
      kWifiNoSignal = 189,
      kWifiOff = 190,
      kWifiOneBar = 191,
      kWifiSecure = 192,
      kWifiSecureNoBar = 193,
      kWifiSecureNoSignal = 194,
      kWifiSecureOneBar = 195,
      kWifiUnknown = 196,
      kWindowNew = 197,
      kWindowPopUpBlock = 198,
      kWindowViewAll = 199,
      kWork = 205,
      kWorkspaces = 200,
      kZoomIn = 201,
      kZoomOut = 202,
    }
    enum EclipseLabelType {
      kT1,
      kT2,
      kT3,
      kT4,
      kT5,
      kT6,
      kT7,
      kB1,
      kB2,
      kB3,
      kB4,
      kC1 = kB4+2,
      kC2,
      kC3,
      kC4,
    }
    enum EclipseButtonType {
      kIcon,
      kIconWithLabel,
      kText,
      kTextWithIcon,
    }
    enum EclipseSliderType {
      kRadialWithIcon,
      kRadialWithIconSmall,
      kHorizontalWithIcon,
      kHorizontalWithLabel,
    }
    class FontParams {
      style: resources.FontStyle;
      weight: resources.FontWeight;
      fontSize: number;
      tracking: number;
      allCaps: boolean;
      constructor(a_style: resources.FontStyle = 0 /* 0 is not the actual default value */, a_weight: resources.FontWeight = 0 /* 0 is not the actual default value */, a_fontSize: number = 0 /* 0 is not the actual default value */, a_tracking: number = 0 /* 0 is not the actual default value */, a_allCaps: boolean = 0 /* 0 is not the actual default value */)
    };
    enum Side {
      kTop,
      kRight,
      kBottom,
      kLeft,
    }
    enum LabelDisplayMode {
      kHover,
      kAlways,
    }
    enum Orientation {
      kVertical,
      kHorizontal,
    }
    enum HorizontalAlignment {
      kLeft,
      kCenter,
      kRight,
    }
    enum VerticalAlignment {
      kTop,
      kCenter,
      kBottom,
    }
    enum PanelEdgeConstraintLevel {
      kNone,
      kLight,
      kMedium,
      kHeavy,
      kImpassable,
      kManual,
    }
    enum PanelCursorTransitionType {
      kClosestEdge,
      kCenter,
      kInitialPosition,
    }
    class Alignment {
      vertical: ui.VerticalAlignment;
      horizontal: ui.HorizontalAlignment;
      constructor(v: ui.VerticalAlignment, h: ui.HorizontalAlignment)
      equals(rhs: ui.Alignment): boolean
      readonly TOP_LEFT: ui.Alignment = Alignment(VerticalAlignment.kTop,HorizontalAlignment.kLeft);
      readonly TOP_CENTER: ui.Alignment = Alignment(VerticalAlignment.kTop,HorizontalAlignment.kCenter);
      readonly TOP_RIGHT: ui.Alignment = Alignment(VerticalAlignment.kTop,HorizontalAlignment.kRight);
      readonly CENTER_LEFT: ui.Alignment = Alignment(VerticalAlignment.kCenter,HorizontalAlignment.kLeft);
      readonly CENTER_CENTER: ui.Alignment = Alignment(VerticalAlignment.kCenter,HorizontalAlignment.kCenter);
      readonly CENTER_RIGHT: ui.Alignment = Alignment(VerticalAlignment.kCenter,HorizontalAlignment.kRight);
      readonly BOTTOM_LEFT: ui.Alignment = Alignment(VerticalAlignment.kBottom,HorizontalAlignment.kLeft);
      readonly BOTTOM_CENTER: ui.Alignment = Alignment(VerticalAlignment.kBottom,HorizontalAlignment.kCenter);
      readonly BOTTOM_RIGHT: ui.Alignment = Alignment(VerticalAlignment.kBottom,HorizontalAlignment.kRight);
    };
    enum ScrollBarVisibility {
      kOff,
      kAuto,
      kAlways,
    }
    enum ScrollDirection {
      kVertical,
      kHorizontal,
    }
    enum CursorEdgeScrollMode {
      kNever,
      kAuto,
      kAlways,
    }
    enum TextEntryMode {
      kNone,
      kNormal,
      kEmail,
      kNumeric,
      kURL,
    }
    enum HorizontalTextAlignment {
      kLeft,
      kCenter,
      kRight,
      kJustify,
    }
    enum SoundEvent {
      kHoverEnter,
      kHoverExit,
      kActivate,
      kLongPress,
      kFocusGained,
      kFocusLost,
      kToggleStateOn,
      kToggleStateOff,
      kDropDownItemHover,
      kDropDownItemSelect,
      kDropDownListExpand,
      kDropDownListCollapse,
      kDropDownNestedListExpand,
      kDropDownNestedListCollapse,
      kTextCursorInsert,
      kTextWordSelect,
      kTextSelectionHandleGrab,
      kTextSelectionHandleDrop,
      kTextPasswordShow,
      kTextPasswordHide,
      kDialogOpen,
      kDialogLoop,
      kDialogConfirm,
      kDialogCancel,
      kContextMenuOpen,
      kContextMenuClose,
      kContextMenuItemHover,
      kContextMenuItemSelect,
      kScrollViewScrollLimit,
      kPanelTransitionHorizontal,
      kPanelTransitionVertical,
    }
    enum DialogType {
      kSingleAction,
      kDualAction,
      kCustom,
      kTimed,
      kNoAction,
    }
    enum DialogLayout {
      kStandard,
      kWide,
    }
    enum TimePeriod {
      kAM,
      kPM,
    }
    const INVALID_COMPONENT_TYPE: number = 0;
  }
}
